# Generated by Django 6.0.1 on 2026-02-01 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('icone', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_bien', models.CharField(choices=[('appartement', 'Appartement'), ('maison', 'Maison'), ('studio', 'Studio'), ('villa', 'Villa')], max_length=20)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('superficie', models.DecimalField(decimal_places=2, max_digits=8)),
                ('nombre_chambres', models.IntegerField()),
                ('nombre_salles_bain', models.IntegerField()),
                ('ville', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_meuble', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('en_attente', 'En attente'), ('desactivee', 'Désactivée'), ('louee', 'Louée')], default='en_attente', max_length=20)),
                ('nombre_vues', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='accounts.proprietaire')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnnonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annonces/')),
                ('is_principale', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annonces.annonce')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['ordre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnnonceEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='annonces.annonce')),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonces.equipement')),
            ],
            options={
                'verbose_name': "Équipement de l'annonce",
                'verbose_name_plural': 'Équipements des annonces',
                'unique_together': {('annonce', 'equipement')},
            },
        ),
    ]
